### ISSUE TITLE
Agent not appearing 

### ISSUE THREAD

**Issue by c0pper** [scrobble-moe/AniList.bundle#11]
Anilist user agent is not showing in the list.
![Screenshot_20221116_214831](https://user-images.githubusercontent.com/18085925/202291079-3929a449-d444-4db1-9503-8108f97fd46a.png)

Absolute series scanner is installed and shows up in Plex.
AniList.bundle is at the following path
`/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/AniList.bundle-2.9/`
Plex media server was stopped and started again.

OS info:
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"

Maybe I'm missing something very simple. Thanks.

**Comment by sachaw** [comment]
The folder name must not be appended with anything, yous ends with "-2.9'
Remove that and try again

**Comment by c0pper** [comment]
Thanks for the quick answer, that was it.
However another issue popped up: I created my library from scratch, selected ASS and AniList scanner, but for any entry that I try to match it doesn't find matches, for example:
![image](https://user-images.githubusercontent.com/18085925/202301344-f1a87d54-6e40-4d67-a27e-b27af59dfe56.png)
![image](https://user-images.githubusercontent.com/18085925/202301480-35b6af56-4b10-4074-8f90-2f54d67914a4.png)

Automatch doesn't work either:
![image](https://user-images.githubusercontent.com/18085925/202301590-d40056e3-522e-4a71-bfd3-9d81deb2ba17.png)

Interesting to note that with this same library it used to work flawlessly on Windows.
Wondering if you or anyone reading can think of something to check or change in my configuration. Thanks again.

**Comment by c0pper** [comment]
I found the log file for the agent and it looks like an exception comes up everytime a search is attempted:
`2022-11-16 22:53:57,563 (7f11715c3b38) :  CRITICAL (agentkit:1018) - Exception in the search function of agent named 'AniList', called with keyword arguments {'show': 'p', 'id': '3592', 'year': None} (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-6d72b0cf6/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1011, in _search
    agent.search(*f_args, **f_kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/AniList.bundle/Contents/Code/__init__.py", line 25, in search
    search_anime('tv', results, media, lang)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/AniList.bundle/Contents/Code/search.py", line 37, in search_anime
    "id": "''' + re.match('^([0-9]*?) ', search_term).group(1) + '''"
AttributeError: 'NoneType' object has no attribute 'group'`


Here's the full log: [me.sachaw.agents.anilist.log](https://github.com/scrobble-moe/AniList.bundle/files/10026039/me.sachaw.agents.anilist.log)

**Comment by sachaw** [comment]
Yeah, the agent was designed to have a neatly ordered anime library, where each series folder is appended with the anilist ID to remove any uncertainty, in search mode it uses the standard anilist search.
If you have suggestions on what to improve I'm open to new ideas.

**Comment by c0pper** [comment]
Thanks for the support btw. Do you have any clue at all about the cause of this regex related error in the log?
`File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/AniList.bundle/Contents/Code/search.py", line 37, in search_anime "id": "''' + re.match('^([0-9]*?) ', search_term).group(1) + '''" AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by sachaw** [comment]
The regex error is because it is looking for the anilist I'd at the start of the folder name, I should catch the error and show a message instead

**Comment by Goten87** [comment]
i can see why you have it that it will check for a anilist id in the name but i think that will not do for me why not look into a folder to see if there is a textfile with the ID in there lets say `anilist.txt` or something and then in there the id of the anime
so where the folders are there is also a file with the ID think that will make it a lot cleaner then have the id in the show name

**Comment by sachaw** [comment]
There are other match methods available, also manually matching may be of use for you.
One thing you mentioned is season folders. Anilist has no concept of show and seasons, each season is its own entry and the Plex agent follows suit.
Why can't you put the id in the name, it's as much effort as creating the txt file you proposed
